#!/bin/bash

cd /home/deck/.rc24

weather_lang=$(cat /home/deck/.rc24/weather_lang)
weather_region=$(cat /home/deck/.rc24/weather_region)
nand_region=$(cat /home/deck/.rc24/nand_region)
news_lang=$(cat /home/deck/.rc24/news_lang)
echo "nand region ${nand_region}"
echo "weather lang ${weather_lang}"
echo "weather region ${weather_region}"
echo "news lang ${news_lang}"

while true
do

	#Run for U
	if [ "$nand_region" = "U" ]
	then
		#Forecast Channel Data Get
		wget http://weather.wii.rc24.xyz/${weather_lang}/${weather_region}/wc24dl.vff
		mv -v wc24dl.vff /home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/Wii/title/00010002/48414645/data/wc24dl.vff
		#News Channel Data Get
		wget http://news.wii.rc24.xyz/v2/${news_lang}/wc24dl.vff
		mv -v wc24dl.vff /home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/Wii/title/00010002/48414745/data/wc24dl.vff
	fi

	#Run for E
	if [ "$nand_region" = "E" ]
	then
		#Forecast Channel Data Get
		wget http://weather.wii.rc24.xyz/${weather_lang}/${weather_region}/wc24dl.vff
		mv -v wc24dl.vff /home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/Wii/title/00010002/48414650/data/wc24dl.vff
		#News Channel Data Get
		wget http://news.wii.rc24.xyz/v2/${news_lang}/wc24dl.vff
		mv -v wc24dl.vff /home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/Wii/title/00010002/48414750/data/wc24dl.vff
	fi

	#Run for J
	if [ "$nand_region" = "J" ]
	then
		#Forecast Channel Data Get
		wget http://weather.wii.rc24.xyz/${weather_lang}/${weather_region}/wc24dl.vff
		mv -v wc24dl.vff /home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/Wii/title/00010002/4841464a/data/wc24dl.vff
		#News Channel Data Get
		wget http://news.wii.rc24.xyz/v2/${news_lang}/wc24dl.vff
		mv -v wc24dl.vff /home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/Wii/title/00010002/4841474a/data/wc24dl.vff
	fi
	sleep 30m
done
